# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("person.proto", :syntax => :proto3) do
    add_message "User" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :email, :string, 3
    end
    add_message "Notification" do
      optional :priority, :string, 1
      optional :msg, :string, 2
    end
    add_enum "Enum" do
      value :LOW, 0
      value :MEDIUM, 1
      value :HIGH, 2
      value :URGENT, 4
    end
  end
end

User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Notification").msgclass
Enum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Enum").enummodule
